# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa08f5ee6f396f23e7d0d7283ccf48a5459292f7eb5c000e643d7726f8e74db0cb3bf7bf519ad22c628e1a6379740324a5ba236c77e30fdb507f1bbf61fec14

test:
  secret_key_base: e739ca435a21265a54d8c2c1ae5f4a94e7116c16a96cdaf8f45519be57f90559caed9ae9f4574ffb9bd79b4b641f3a7415d33e53022bee8910f98440e55b7503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
